"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addtagtablerequest import AddTagTableRequest, AddTagTableRequestTypedDict
from meibelai.types import BaseModel
from meibelai.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing_extensions import Annotated, TypedDict


class AddTagTableInfoRequestTypedDict(TypedDict):
    datasource_id: str
    table_name: str
    customer_id: str
    r"""Customer ID"""
    add_tag_table_request: AddTagTableRequestTypedDict


class AddTagTableInfoRequest(BaseModel):
    datasource_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    table_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    customer_id: Annotated[
        str,
        pydantic.Field(alias="customer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Customer ID"""

    add_tag_table_request: Annotated[
        AddTagTableRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
