"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addactivityrequest import AddActivityRequest, AddActivityRequestTypedDict
from meibelai.types import BaseModel
from meibelai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class AddActivityByBlueprintInstanceRequestTypedDict(TypedDict):
    blueprint_instance_id: str
    add_activity_request: AddActivityRequestTypedDict


class AddActivityByBlueprintInstanceRequest(BaseModel):
    blueprint_instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    add_activity_request: Annotated[
        AddActivityRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
