"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addtagconfigrequest import AddTagConfigRequest, AddTagConfigRequestTypedDict
from meibelai.types import BaseModel
from meibelai.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing_extensions import Annotated, TypedDict


class AddTagConfigRequest1TypedDict(TypedDict):
    datasource_id: str
    customer_id: str
    r"""Customer ID"""
    add_tag_config_request: AddTagConfigRequestTypedDict


class AddTagConfigRequest1(BaseModel):
    datasource_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    customer_id: Annotated[
        str,
        pydantic.Field(alias="customer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Customer ID"""

    add_tag_config_request: Annotated[
        AddTagConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
