"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addchunkingstrategyrequest import (
    AddChunkingStrategyRequest,
    AddChunkingStrategyRequestTypedDict,
)
from meibelai.types import BaseModel
from meibelai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class AddChunkingStrategyRequest1TypedDict(TypedDict):
    datasource_id: str
    add_chunking_strategy_request: AddChunkingStrategyRequestTypedDict


class AddChunkingStrategyRequest1(BaseModel):
    datasource_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    add_chunking_strategy_request: Annotated[
        AddChunkingStrategyRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
