"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adddatasourcerequest import AddDatasourceRequest, AddDatasourceRequestTypedDict
from meibelai.types import BaseModel
from meibelai.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class AddDatasourceRequest1TypedDict(TypedDict):
    customer_id_param: str
    r"""Customer ID"""
    add_datasource_request: AddDatasourceRequestTypedDict


class AddDatasourceRequest1(BaseModel):
    customer_id_param: Annotated[
        str,
        pydantic.Field(alias="customer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Customer ID"""

    add_datasource_request: Annotated[
        AddDatasourceRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
