"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dsldefinition import DslDefinition
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class AddBlueprintRequestTypedDict(TypedDict):
    r"""AddBlueprintRequest"""

    name: str
    dsl_definition: DslDefinition
    r"""DslDefinition"""
    execution_mode: NotRequired[Nullable[str]]
    version: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]
    yaml_spec_content: NotRequired[Nullable[str]]
    json_spec_content: NotRequired[Nullable[Dict[str, Any]]]
    workflow_type: NotRequired[Nullable[str]]
    workflow_task_queue: NotRequired[Nullable[str]]
    init_input: NotRequired[Nullable[Dict[str, Any]]]


class AddBlueprintRequest(BaseModel):
    r"""AddBlueprintRequest"""

    name: str

    dsl_definition: DslDefinition
    r"""DslDefinition"""

    execution_mode: OptionalNullable[str] = UNSET

    version: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET

    yaml_spec_content: OptionalNullable[str] = UNSET

    json_spec_content: OptionalNullable[Dict[str, Any]] = UNSET

    workflow_type: OptionalNullable[str] = UNSET

    workflow_task_queue: OptionalNullable[str] = UNSET

    init_input: OptionalNullable[Dict[str, Any]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "execution_mode",
                "version",
                "description",
                "yaml_spec_content",
                "json_spec_content",
                "workflow_type",
                "workflow_task_queue",
                "init_input",
            ]
        )
        nullable_fields = set(
            [
                "execution_mode",
                "version",
                "description",
                "yaml_spec_content",
                "json_spec_content",
                "workflow_type",
                "workflow_task_queue",
                "init_input",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
