"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasourcewebconfig import DatasourceWebConfig, DatasourceWebConfigTypedDict
from .objectstorageconfig import ObjectStorageConfig, ObjectStorageConfigTypedDict
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class AddDatasourceRequestTypedDict(TypedDict):
    r"""AddDatasourceRequest"""

    customer_id: str
    project_id: str
    name: str
    description: str
    recurrence: str
    object_storage_config: NotRequired[Nullable[ObjectStorageConfigTypedDict]]
    web_config: NotRequired[Nullable[DatasourceWebConfigTypedDict]]


class AddDatasourceRequest(BaseModel):
    r"""AddDatasourceRequest"""

    customer_id: str

    project_id: str

    name: str

    description: str

    recurrence: str

    object_storage_config: OptionalNullable[ObjectStorageConfig] = UNSET

    web_config: OptionalNullable[DatasourceWebConfig] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object_storage_config", "web_config"])
        nullable_fields = set(["object_storage_config", "web_config"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
