"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class AddReferenceGraphConfigRequestTypedDict(TypedDict):
    r"""AddReferenceGraphConfigRequest"""

    endpoint: str
    db_name: str
    doc_collection: str
    ref_collection: str


class AddReferenceGraphConfigRequest(BaseModel):
    r"""AddReferenceGraphConfigRequest"""

    endpoint: str

    db_name: str

    doc_collection: str

    ref_collection: str
