"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatresponse import ChatResponse, ChatResponseTypedDict
from .toolactivity import ToolActivity, ToolActivityTypedDict
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List
from typing_extensions import NotRequired, TypedDict


class ChatMessageResponseTypedDict(TypedDict):
    r"""Response from the non-streaming chat endpoint."""

    signal_id: str
    r"""Unique ID for this message exchange"""
    response: ChatResponseTypedDict
    r"""The structured chat response."""
    assistant_response: str
    r"""The assistant response in text-format"""
    tool_activity: NotRequired[Nullable[List[ToolActivityTypedDict]]]
    thinking: NotRequired[Nullable[str]]
    token_usage: NotRequired[Nullable[Dict[str, int]]]


class ChatMessageResponse(BaseModel):
    r"""Response from the non-streaming chat endpoint."""

    signal_id: str
    r"""Unique ID for this message exchange"""

    response: ChatResponse
    r"""The structured chat response."""

    assistant_response: str
    r"""The assistant response in text-format"""

    tool_activity: OptionalNullable[List[ToolActivity]] = UNSET

    thinking: OptionalNullable[str] = UNSET

    token_usage: OptionalNullable[Dict[str, int]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tool_activity", "thinking", "token_usage"])
        nullable_fields = set(["tool_activity", "thinking", "token_usage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
