"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ChatMessageRequestTypedDict(TypedDict):
    r"""Request body for chat message endpoints."""

    user_message: str
    r"""The user's chat message"""
    timeout_seconds: NotRequired[Nullable[int]]
    include_thinking: NotRequired[Nullable[bool]]
    include_tool_activity: NotRequired[Nullable[bool]]


class ChatMessageRequest(BaseModel):
    r"""Request body for chat message endpoints."""

    user_message: str
    r"""The user's chat message"""

    timeout_seconds: OptionalNullable[int] = UNSET

    include_thinking: OptionalNullable[bool] = UNSET

    include_tool_activity: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["timeout_seconds", "include_thinking", "include_tool_activity"]
        )
        nullable_fields = set(
            ["timeout_seconds", "include_thinking", "include_tool_activity"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
