"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from meibelai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ConnectedEventDataTypedDict(TypedDict):
    signal_id: str
    r"""Unique identifier for this stream connection"""


class ConnectedEventData(BaseModel):
    signal_id: str
    r"""Unique identifier for this stream connection"""


class ConnectedEventTypedDict(TypedDict):
    r"""A server-sent event indicating the stream connection has been established"""

    data: ConnectedEventDataTypedDict
    event: Literal["connected"]


class ConnectedEvent(BaseModel):
    r"""A server-sent event indicating the stream connection has been established"""

    data: ConnectedEventData

    EVENT: Annotated[
        Annotated[Literal["connected"], AfterValidator(validate_const("connected"))],
        pydantic.Field(alias="event"),
    ] = "connected"


try:
    ConnectedEvent.model_rebuild()
except NameError:
    pass
