"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing import Union
from typing_extensions import TypeAliasType, TypedDict


SizeTypedDict = TypeAliasType("SizeTypedDict", Union[float, int])


Size = TypeAliasType("Size", Union[float, int])


class DataElementDiscoveryRecordTypedDict(TypedDict):
    r"""DataElementDiscoveryRecord"""

    discovery_time: str
    last_modified_time: str
    size: SizeTypedDict
    element_hash: str


class DataElementDiscoveryRecord(BaseModel):
    r"""DataElementDiscoveryRecord"""

    discovery_time: str

    last_modified_time: str

    size: Size

    element_hash: str
