"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


SizeTypedDict = TypeAliasType("SizeTypedDict", Union[float, int])


Size = TypeAliasType("Size", Union[float, int])


class DataElementDiscoveryRecordTypedDict(TypedDict):
    r"""DataElementDiscoveryRecord"""

    discovery_time: str
    last_modified_time: str
    size: SizeTypedDict
    element_hash: str
    file_id: NotRequired[Nullable[str]]
    file_created_at: NotRequired[Nullable[str]]
    file_modified_at: NotRequired[Nullable[str]]
    extra: NotRequired[Nullable[Dict[str, Any]]]
    r"""Connector-specific extra metadata"""


class DataElementDiscoveryRecord(BaseModel):
    r"""DataElementDiscoveryRecord"""

    discovery_time: str

    last_modified_time: str

    size: Size

    element_hash: str

    file_id: OptionalNullable[str] = UNSET

    file_created_at: OptionalNullable[str] = UNSET

    file_modified_at: OptionalNullable[str] = UNSET

    extra: OptionalNullable[Dict[str, Any]] = UNSET
    r"""Connector-specific extra metadata"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["file_id", "file_created_at", "file_modified_at", "extra"]
        )
        nullable_fields = set(
            ["file_id", "file_created_at", "file_modified_at", "extra"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
