"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DatasourceType(str, Enum):
    DEFAULT = "default"
    GCS = "gcs"
    GOOGLE_DRIVE = "google-drive"
    S3 = "s3"
    WEBSITE = "website"
    YOUTUBE = "youtube"
