"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DeleteContentResponseTypedDict(TypedDict):
    r"""DeleteContentResponse"""

    success: bool
    deleted_paths: List[str]


class DeleteContentResponse(BaseModel):
    r"""DeleteContentResponse"""

    success: bool

    deleted_paths: List[str]
