"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class EmbeddingModelTypedDict(TypedDict):
    r"""EmbeddingModel"""

    name: str
    endpoint: str
    dimensions: int


class EmbeddingModel(BaseModel):
    r"""EmbeddingModel"""

    name: str

    endpoint: str

    dimensions: int
