"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class ExtractorModelTypedDict(TypedDict):
    r"""ExtractorModel"""

    name: str
    endpoint: str


class ExtractorModel(BaseModel):
    r"""ExtractorModel"""

    name: str

    endpoint: str
