"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gatewaymetadata import GatewayMetadata, GatewayMetadataTypedDict
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class GatewayNewDatasourceRequestTypedDict(TypedDict):
    description: str
    name: str
    type: str
    metadata: GatewayMetadataTypedDict


class GatewayNewDatasourceRequest(BaseModel):
    description: str

    name: str

    type: str

    metadata: GatewayMetadata
