"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contenttype import ContentType
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class GetContentResponseTypedDict(TypedDict):
    r"""GetContentResponse"""

    name: str
    path: str
    type: ContentType
    r"""ContentType"""
    size: NotRequired[Nullable[int]]
    media_type: NotRequired[Nullable[str]]
    last_modified: NotRequired[Nullable[str]]
    etag: NotRequired[Nullable[str]]
    metadata: NotRequired[Nullable[Dict[str, Any]]]


class GetContentResponse(BaseModel):
    r"""GetContentResponse"""

    name: str

    path: str

    type: ContentType
    r"""ContentType"""

    size: OptionalNullable[int] = UNSET

    media_type: OptionalNullable[str] = UNSET

    last_modified: OptionalNullable[str] = UNSET

    etag: OptionalNullable[str] = UNSET

    metadata: OptionalNullable[Dict[str, Any]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["size", "media_type", "last_modified", "etag", "metadata"]
        )
        nullable_fields = set(
            ["size", "media_type", "last_modified", "etag", "metadata"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
