"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class GetDataElementByPathRequestTypedDict(TypedDict):
    r"""GetDataElementByPathRequest"""

    path: str


class GetDataElementByPathRequest(BaseModel):
    r"""GetDataElementByPathRequest"""

    path: str
