"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ingestmethod import IngestMethod
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class IngestRecordTypedDict(TypedDict):
    r"""IngestRecord"""

    datasource_id: str
    data_element_id: str
    ingest_method: IngestMethod
    r"""IngestMethod"""
    ingest_time: str
    element_hash: str


class IngestRecord(BaseModel):
    r"""IngestRecord"""

    datasource_id: str

    data_element_id: str

    ingest_method: IngestMethod
    r"""IngestMethod"""

    ingest_time: str

    element_hash: str
