"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class MetadataFieldDefinitionTypedDict(TypedDict):
    r"""MetadataFieldDefinition"""

    name: str
    type: str
    description: str


class MetadataFieldDefinition(BaseModel):
    r"""MetadataFieldDefinition"""

    name: str

    type: str

    description: str
