"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ObjectStorageFiltersTypedDict(TypedDict):
    r"""ObjectStorageFilters"""

    included_prefixes: NotRequired[Nullable[List[str]]]
    included_file_types: NotRequired[Nullable[List[str]]]
    recursive_prefixes: NotRequired[Nullable[bool]]
    modified_date_start: NotRequired[Nullable[str]]
    modified_date_end: NotRequired[Nullable[str]]
    min_file_size: NotRequired[Nullable[int]]
    max_file_size: NotRequired[Nullable[int]]


class ObjectStorageFilters(BaseModel):
    r"""ObjectStorageFilters"""

    included_prefixes: OptionalNullable[List[str]] = UNSET

    included_file_types: OptionalNullable[List[str]] = UNSET

    recursive_prefixes: OptionalNullable[bool] = UNSET

    modified_date_start: OptionalNullable[str] = UNSET

    modified_date_end: OptionalNullable[str] = UNSET

    min_file_size: OptionalNullable[int] = UNSET

    max_file_size: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "included_prefixes",
                "included_file_types",
                "recursive_prefixes",
                "modified_date_start",
                "modified_date_end",
                "min_file_size",
                "max_file_size",
            ]
        )
        nullable_fields = set(
            [
                "included_prefixes",
                "included_file_types",
                "recursive_prefixes",
                "modified_date_start",
                "modified_date_end",
                "min_file_size",
                "max_file_size",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
