"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .patchragconfigmetadatarequest import (
    PatchRagConfigMetadataRequest,
    PatchRagConfigMetadataRequestTypedDict,
)
from meibelai.types import BaseModel
from meibelai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PatchRagConfigMetadataRequest1TypedDict(TypedDict):
    datasource_id: str
    patch_rag_config_metadata_request: PatchRagConfigMetadataRequestTypedDict


class PatchRagConfigMetadataRequest1(BaseModel):
    datasource_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    patch_rag_config_metadata_request: Annotated[
        PatchRagConfigMetadataRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
