"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class Platform(str, Enum):
    r"""Platform"""

    AZURE = "azure"
    GCS = "gcs"
    R2 = "r2"
    S3 = "s3"
