"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scoringjobrecord import ScoringJobRecord, ScoringJobRecordTypedDict
from .scoringstatus import ScoringStatus
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


AggregateScoreTypedDict = TypeAliasType("AggregateScoreTypedDict", Union[float, int])


AggregateScore = TypeAliasType("AggregateScore", Union[float, int])


ModuleScoresTypedDict = TypeAliasType("ModuleScoresTypedDict", Union[float, int])


ModuleScores = TypeAliasType("ModuleScores", Union[float, int])


class ScoreSummaryTypedDict(TypedDict):
    r"""Aggregated summary of scoring jobs matching one or two AgentIdentityContext filters.  With one level (primary only): flat aggregate of all jobs matching primary_field=primary_value. With two levels (primary + secondary): both constraints are applied; primary is the higher level and secondary is the lower level."""

    primary_field: str
    primary_value: str
    secondary_field: NotRequired[Nullable[str]]
    secondary_value: NotRequired[Nullable[str]]
    status: NotRequired[Nullable[ScoringStatus]]
    aggregate_score: NotRequired[Nullable[AggregateScoreTypedDict]]
    module_scores: NotRequired[Nullable[Dict[str, ModuleScoresTypedDict]]]
    n_jobs_per_module: NotRequired[Nullable[Dict[str, int]]]
    jobs: NotRequired[Nullable[List[ScoringJobRecordTypedDict]]]


class ScoreSummary(BaseModel):
    r"""Aggregated summary of scoring jobs matching one or two AgentIdentityContext filters.  With one level (primary only): flat aggregate of all jobs matching primary_field=primary_value. With two levels (primary + secondary): both constraints are applied; primary is the higher level and secondary is the lower level."""

    primary_field: str

    primary_value: str

    secondary_field: OptionalNullable[str] = UNSET

    secondary_value: OptionalNullable[str] = UNSET

    status: OptionalNullable[ScoringStatus] = UNSET

    aggregate_score: OptionalNullable[AggregateScore] = UNSET

    module_scores: OptionalNullable[Dict[str, ModuleScores]] = UNSET

    n_jobs_per_module: OptionalNullable[Dict[str, int]] = UNSET

    jobs: OptionalNullable[List[ScoringJobRecord]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "secondary_field",
                "secondary_value",
                "status",
                "aggregate_score",
                "module_scores",
                "n_jobs_per_module",
                "jobs",
            ]
        )
        nullable_fields = set(
            [
                "secondary_field",
                "secondary_value",
                "status",
                "aggregate_score",
                "module_scores",
                "n_jobs_per_module",
                "jobs",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
