"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatmessagerequest import ChatMessageRequest, ChatMessageRequestTypedDict
from .completionevent import CompletionEvent, CompletionEventTypedDict
from .connectedevent import ConnectedEvent, ConnectedEventTypedDict
from .partialresponseevent import PartialResponseEvent, PartialResponseEventTypedDict
from .statusevent import StatusEvent, StatusEventTypedDict
from .toolcallevent import ToolCallEvent, ToolCallEventTypedDict
from .toolresultevent import ToolResultEvent, ToolResultEventTypedDict
from meibelai.types import BaseModel
from meibelai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class SendChatMessageStreamRequestTypedDict(TypedDict):
    blueprint_instance_id: str
    chat_message_request: ChatMessageRequestTypedDict


class SendChatMessageStreamRequest(BaseModel):
    blueprint_instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    chat_message_request: Annotated[
        ChatMessageRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


SendChatMessageStreamResponseBodyTypedDict = TypeAliasType(
    "SendChatMessageStreamResponseBodyTypedDict",
    Union[
        ConnectedEventTypedDict,
        StatusEventTypedDict,
        ToolCallEventTypedDict,
        ToolResultEventTypedDict,
        PartialResponseEventTypedDict,
        CompletionEventTypedDict,
    ],
)
r"""Successful Response"""


SendChatMessageStreamResponseBody = Annotated[
    Union[
        ConnectedEvent,
        StatusEvent,
        ToolCallEvent,
        ToolResultEvent,
        PartialResponseEvent,
        CompletionEvent,
    ],
    Field(discriminator="EVENT"),
]
r"""Successful Response"""
