"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class SentenceChunkingTypedDict(TypedDict):
    r"""SentenceChunking"""

    chunk_size: NotRequired[Nullable[int]]
    chunk_overlap: NotRequired[Nullable[int]]
    separator: NotRequired[Nullable[str]]
    paragraph_separator: NotRequired[Nullable[str]]
    secondary_chunking_regex: NotRequired[Nullable[str]]


class SentenceChunking(BaseModel):
    r"""SentenceChunking"""

    chunk_size: OptionalNullable[int] = UNSET

    chunk_overlap: OptionalNullable[int] = UNSET

    separator: OptionalNullable[str] = UNSET

    paragraph_separator: OptionalNullable[str] = UNSET

    secondary_chunking_regex: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "chunk_size",
                "chunk_overlap",
                "separator",
                "paragraph_separator",
                "secondary_chunking_regex",
            ]
        )
        nullable_fields = set(
            [
                "chunk_size",
                "chunk_overlap",
                "separator",
                "paragraph_separator",
                "secondary_chunking_regex",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
