"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class ToolActivityTypedDict(TypedDict):
    r"""Record of a tool call and its result."""

    tool_id: str
    tool_name: str
    arguments: Dict[str, Any]
    timestamp: str
    result: NotRequired[Nullable[Dict[str, Any]]]


class ToolActivity(BaseModel):
    r"""Record of a tool call and its result."""

    tool_id: str

    tool_name: str

    arguments: Dict[str, Any]

    timestamp: str

    result: OptionalNullable[Dict[str, Any]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["result"])
        nullable_fields = set(["result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
