"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel
from typing_extensions import TypedDict


class UpdateChunkingStrategyResponseTypedDict(TypedDict):
    r"""UpdateChunkingStrategyResponse"""

    message: str


class UpdateChunkingStrategyResponse(BaseModel):
    r"""UpdateChunkingStrategyResponse"""

    message: str
