"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meibelai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class UpdateReferenceGraphConfigRequestTypedDict(TypedDict):
    r"""UpdateReferenceGraphConfigRequest"""

    endpoint: NotRequired[Nullable[str]]
    db_name: NotRequired[Nullable[str]]
    doc_collection: NotRequired[Nullable[str]]
    ref_collection: NotRequired[Nullable[str]]


class UpdateReferenceGraphConfigRequest(BaseModel):
    r"""UpdateReferenceGraphConfigRequest"""

    endpoint: OptionalNullable[str] = UNSET

    db_name: OptionalNullable[str] = UNSET

    doc_collection: OptionalNullable[str] = UNSET

    ref_collection: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["endpoint", "db_name", "doc_collection", "ref_collection"]
        nullable_fields = ["endpoint", "db_name", "doc_collection", "ref_collection"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
