"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatetagconfigrequest import (
    UpdateTagConfigRequest,
    UpdateTagConfigRequestTypedDict,
)
from meibelai.types import BaseModel
from meibelai.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing_extensions import Annotated, TypedDict


class UpdateTagConfigRequest1TypedDict(TypedDict):
    datasource_id: str
    customer_id: str
    r"""Customer ID"""
    update_tag_config_request: UpdateTagConfigRequestTypedDict


class UpdateTagConfigRequest1(BaseModel):
    datasource_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    customer_id: Annotated[
        str,
        pydantic.Field(alias="customer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Customer ID"""

    update_tag_config_request: Annotated[
        UpdateTagConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
