"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_uploaddatasourcecontent import (
    BodyUploadDatasourceContent,
    BodyUploadDatasourceContentTypedDict,
)
from meibelai.types import BaseModel
from meibelai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UploadDatasourceContentRequestTypedDict(TypedDict):
    datasource_id: str
    body_upload_datasource_content: BodyUploadDatasourceContentTypedDict


class UploadDatasourceContentRequest(BaseModel):
    datasource_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body_upload_datasource_content: Annotated[
        BodyUploadDatasourceContent,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]
