workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Meibel Gateway Service:
        inputs:
            - location: https://storage.googleapis.com/meibel-api-docs/api.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/meibel/console/meibel-gateway-service
targets:
    meibelai:
        target: python
        source: Meibel Gateway Service
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/meibel/console/meibel-gateway-service-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
